### ISSUE TITLE
Crawler ignore cyrillic paths in robots.txt

### ISSUE THREAD

**Issue by Lord-Protector** [yacy/yacy_search_server#80] opened 2016-10-10 06:30 UTC
I just index some site with MediaWiki Engine and it's have robots.txt lilke:

```
User-agent: *
Disallow: /%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD:
Disallow: /%D0%A1%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%BE:
Disallow: /%D0%A1%D0%BB%D1%83%D0%B6%D0%B5%D0%B1%D0%BD%D0%B0%D1%8F:
Disallow: /%D0%A3%D1%87%D0%B0%D1%81%D1%82%D0%BD%D0%B8%D0%BA:
```

But in Crawler answers `robots exist: crawl allowed`. It's at least strange...

**Comment by luccioman** [comment] 2016-10-11 07:16
Hi @Lord-Protector you are using the /CrawlCheck_p.html page isn't it? It only gives you info about the exact URL(s) you type in the input field and not about subpathes...
Did you typed for example http://thehost/%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD: ? Is it a public Wiki so we can also try to reproduce the probelm?

**Comment by Lord-Protector** [comment] 2016-10-11 07:43
@luccioman, yes, it's public -- overwiki.ru.
Try and reproduce it too.

**Comment by luccioman** [comment] 2016-10-12 06:11
Ok, I found my way in the cyrillic characters ;), and yes it looks like something effectively needs to be fixed. 

Example URL : https://overwiki.ru/%D0%A1%D0%BB%D1%83%D0%B6%D0%B5%D0%B1%D0%BD%D0%B0%D1%8F:%D0%A1%D0%BF%D0%B5%D1%86%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%8B 
should be detected as not allowed by YaCy as it contains the prefix /%D0%A3%D1%87%D0%B0%D1%81%D1%82%D0%BD%D0%B8%D0%BA:

I am not sure it is related to cyrillic chars, but I will have a check as soon as I have some time.

**Comment by luccioman** [comment] 2016-10-12 09:34
@Lord-Protector I committed a fix : non ASCII URLs were effectively not properly handled when checking robots entries.
I also fixed another point : disallowed entries were not displayed in the /CrawlCheck_p.html result.

If you have some time to test from latest sources, feedback is welcome!

**Closed** 2016-11-03 01:46 UTC
