### ISSUE TITLE
Cannot compile under Freebsd

### ISSUE THREAD

**Issue by okybaca** [yacy/yacy_search_server#468] opened 2022-03-11 16:56 UTC
Compilation (ant clean all) under FreeBSD results in error involving HazelCast:
```
    [javac] Compiling 656 source files to /usr/home/yacy/yacy-src/yacy_search_server/build/classes/java/main
    [javac] /usr/home/yacy/yacy-src/yacy_search_server/lib/hazelcast-4.2.jar(com/hazelcast/config/cp/CPSubsystemConfig.class): warning: Cannot find annotation method 'value()' in type 'SuppressFBWarnings': class file for edu.umd.cs.findbugs.annotations.SuppressFBWarnings not found
    [javac] /usr/home/yacy/yacy-src/yacy_search_server/lib/hazelcast-4.2.jar(com/hazelcast/config/cp/CPSubsystemConfig.class): warning: Cannot find annotation method 'justification()' in type 'SuppressFBWarnings'
    [javac] 2 warnings

```
compilation also returns: 
```

   [gitRev] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
   [gitRev] SLF4J: Defaulting to no-operation (NOP) logger implementation
   [gitRev] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by thkoch2001** [comment] 2022-04-07 08:37
Thank you for your interest. However the two snippets seem to show only warnings, no errors. These warnings are most probably not the cause of a failed build.

Could you post (e.g. as a file attachment) the full output of the failed ant run please? What exact version / commit of YaCy are you trying to compile?

**Comment by okybaca** [comment] 2022-04-09 16:15
Hi, Thank you for a kind reply!

I use master branch synced out of github (1.925 10274). 
You're true, these are actually warnings only, more specificaly:
```
    [javac] /usr/home/yacy/yacy-src/yacy_search_server/lib/hazelcast-4.2.jar(com/hazelcast/config/cp/CPSubsystemConfig.class): warning: Cannot find annotation method 'value()' in type 'SuppressFBWarnings': class file for edu.umd.cs.findbugs.annotations.SuppressFBWarnings not found
    [javac] /usr/home/yacy/yacy-src/yacy_search_server/lib/hazelcast-4.2.jar(com/hazelcast/config/cp/CPSubsystemConfig.class): warning: Cannot find annotation method 'justification()' in type 'SuppressFBWarnings'
    [javac] 2 warnings
```


But after compilation and wile trying to run, YaCy throws only errors (involving HazelCast) and doesn't start, that's why I suspect these HazelCast warnings:
```
I 2022/04/09 16:41:05 com.hazelcast.system [192.168.1.84]:5701 [YaCyP2P] [4.2] Hazelcast 4.2 (20210324 - 405cfd1) starting at [192.168.1.84]:5701
E 2022/04/09 16:41:05 com.hazelcast.instance.impl.Node [192.168.1.84]:5701 [YaCyP2P] [4.2] Invalid argument
java.net.SocketException: Invalid argument
	at java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:178)
	at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323)
	at com.hazelcast.internal.cluster.impl.MulticastService.createMulticastService(MulticastService.java:142)
	at com.hazelcast.instance.impl.Node.<init>(Node.java:274)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:148)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
	at net.yacy.search.Switchboard.<init>(Switchboard.java:668)
	at net.yacy.yacy.startup(yacy.java:211)
	at net.yacy.yacy.main(yacy.java:828)
E 2022/04/09 16:41:05 com.hazelcast.instance.impl.Node [192.168.1.84]:5701 [YaCyP2P] [4.2] Node creation failed
com.hazelcast.core.HazelcastException: Starting the MulticastService failed
	at com.hazelcast.internal.cluster.impl.MulticastService.createMulticastService(MulticastService.java:150)
	at com.hazelcast.instance.impl.Node.<init>(Node.java:274)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:148)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
	at net.yacy.search.Switchboard.<init>(Switchboard.java:668)
	at net.yacy.yacy.startup(yacy.java:211)
	at net.yacy.yacy.main(yacy.java:828)
Caused by: java.net.SocketException: Invalid argument
	at java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:178)
	at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323)
	at com.hazelcast.internal.cluster.impl.MulticastService.createMulticastService(MulticastService.java:142)
	... 10 more

```

Verbose compile log is attached. 
Thank you for an advice or fix!
[compile.log](https://github.com/yacy/yacy_search_server/files/8457320/compile.log)

**Comment by Orbiter** [comment] 2022-04-09 22:15
That hazelcast was an experiment. I tried around with hazelcast in YaCy Grid as well and it was a huge problem. We probably do not need it in YaCy.

**Comment by okybaca** [comment] 2022-04-17 11:52
Great, thanks for the explanation, @Orbiter! So what to do now? If the hazelcast is not used any more, could you please remove it, so it doesn't stuck? Thanks!

**Comment by Orbiter** [comment] 2022-04-17 14:15
Sorry for the delay, I am on Easter holiday... I will check this soon after my return

**Comment by okybaca** [comment] 2022-04-18 08:57
Thanks, Michael, and happy Easter!

**Comment by okybaca** [comment] 2022-06-20 09:38
hi, it's been already several months again and still not fixed. could you please someone just revert the commit [https://github.com/yacy/yacy_search_server/commit/1cdb21592bdf83424b3d4e1b4c954eec933750ef]? thanks!

**Comment by Orbiter** [comment] 2022-06-20 15:28
sorry for that, should be fixed now

**Closed** 2022-06-20 15:27 UTC
Labels: developer issue, more info needed
