### ISSUE TITLE
LibreJS

### ISSUE THREAD

**Issue by 539h** [yacy/yacy_search_server#24] opened 2015-11-12 20:24 UTC
LibreJS is blocking the javascript because it doesn't detect the licenses. I'll try to fix it myself.

**Comment by bshouse** [comment] 2015-12-16 03:49
Just doing some research and LibreJS is a plugin that allows users to block non-free JavaScript that may be served by YaCy, but not produced by it.

HowTo: http://www.gnu.org/software/librejs/free-your-javascript.html (Step 3)
HowTo (Google Cache since site was down): http://webcache.googleusercontent.com/search?q=cache:SmnyznRjELMJ:www.gnu.org/software/librejs/free-your-javascript.html+&cd=1&hl=en&ct=clnk&gl=us

It sounds like it is worth the effort and aligns with the spirit of this project.

Any thing I can do to assist?

**Comment by luccioman** [comment] 2016-02-22 00:09
This looks like to be a duplicate of existing issue on YaCy Mantis tracker : http://mantis.tokeek.de/view.php?id=284
I think a good starting point to help would be to apply LibreJs HowTo on https://github.com/yacy/yacy_search_server/blob/master/htroot/index.html

**Comment by luccioman** [comment] 2016-06-03 20:28
Ok I applied LibreJs instructions on main YaCy landing page and it works fine : see branch https://github.com/luccioman/yacy_search_server/tree/LibreJS.
There is still some work to make whole YaCy compatible but it is not so a big deal.

**Comment by Orbiter** [comment] 2016-07-04 19:17
should be fixed with pull https://github.com/yacy/yacy_search_server/commit/50c5ddf1a16d7b123c73646a0bac08ff4f228a21

**Closed by Orbiter** 2016-07-04 19:17 UTC
